### ISSUE TITLE
Error running jq: UnicodeDecodeError

### ISSUE THREAD

**Issue by philipp-siegmantel** [kislyuk/yq#101]
When running yq on our Linux CI machine, i get the following error:
```
yq: Error running jq: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 71: ordinal not in range(128).
```
It works just fine on locally my MacBook. yq version is 2.10.1.

It is called like this:
```
yq 'with_entries(.value = .value.en)' translations/translations.yml > en.json
```

**Comment by kislyuk** [comment]
This happens when you install yq using Python 2, which is no longer supported. To install yq using Python 3, run `pip3 install yq` instead of `pip install yq`. The yq docs are out of date on this point - I'm going to update them.

**Comment by kislyuk** [comment]
Updated docs to mention pip3.
