### ISSUE TITLE
Possible special character bug

### ISSUE THREAD

**Issue by mvrozanti** [kislyuk/yq#105]
When [this](http://ix.io/2AZl) xml is read by yq with `curl -s http://feeds.bbci.co.uk/news/rss.xml | yq`, it outputs the following error:

```
yq: Error running jq: ScannerError: mapping values are not allowed here
  in "<stdin>", line 15, column 38.
```

Maybe it's having it with the ! exclamation mark in there? I'm just guessing. That xml should be valid.

**Comment by kislyuk** [comment]
The yq utility does not accept XML input. You need to pipe your XML to `xq` instead (which is bundled with yq).
