### ISSUE TITLE
Why does yq output ... at the end?

### ISSUE THREAD

**Issue by rayzorben** [kislyuk/yq#109]
Example:

```yaml
user:
  name: Ray
```
Output
```
~/source » yq -Y .user.name arch.yml                                       2 ↵ rayben@rayarchpad
Ray
...
```

**Comment by rayzorben** [comment]
Similarly, yq -y with some expressions puts `-` at the beginning:

```yaml
user:
  name: Ray
```
Output of `yq -y '..' file.yml`
```
user:
  name: Ray
---
name: Ray
--- Ray
...
```

But this one is really odd:

`yq -Y '.. | tostring | startswith("!secret")' file.yml` outputs:

```yaml
~/source » yq -Y '.. | tostring | startswith("!secret")' arch.yml              rayben@rayarchpad
false
--- false
--- false
--- true
--- false
--- false
--- false
```

**Comment by kislyuk** [comment]
Please see #104.

**Comment by rayzorben** [comment]
Any idea on the second issue though or are they related and will both be
fixed at the same time?

**Comment by kislyuk** [comment]
That is a different issue, actually. You asked yq to translate a stream of multiple JSON documents back into YAML. But in YAML, unlike JSON, there is no unambiguous way to distinguish between a document boundary and a continuation of the existing document. So you will see PyYAML emit document separators (`---`) in this case. Like #104, it's not a bug but an artifact of YAML/PyYAML's behavior, but unlike #104, I don't think there's anything expected in the future to control this behavior. To avoid it, you can just not use `-y`/`-Y`.

**Comment by kislyuk** [comment]
It may be that in your last example there are missing newlines, though. I'll take a look at that (#110).

**Comment by rayzorben** [comment]
Thanks, I guess what I am looking for may not be possible at this time (or have to use sed/grep/etc):

I want to take the following:

```
user:
  password: !secret U4e80asdfnkjlasdf832r/u0q80sa
  name: ray

...
```

And I want to say 'are there any values in this document (one or more) that contain the tag `!secret` (which I know is a yaml thing and not a json thing).

And then I want to say

`cat file.yml | yq '.user.password | tags'` > would return `!secret`
`cat file.yml | yq .user.password` > would return `U4e80asdfnkjlasdf832r/u0q80sa`

That way I know what I am reading is an encrypted value.
