### ISSUE TITLE
make a brew package

### ISSUE THREAD

**Issue by ahmetb** [kislyuk/yq#11]
`jq` has a homebrew package. It would be good to have one for `yq` as well.

**Comment by kislyuk** [comment]
Thanks for the suggestion, but I'm not quite sure where to start. Someone more plugged in to the homebrew ecosystem will have to guide me.

**Comment by ndeloof** [comment]
it's there already : https://github.com/Homebrew/homebrew-core/blob/master/Formula/yq.rb

**Comment by lonkaut** [comment]
I have installed yq via brew but xq doesn't exist.  What am I missing?

**Comment by kislyuk** [comment]
@lonkaut, the yq package in homebrew is a different package, not related to this yq.

**Comment by kislyuk** [comment]
Homebrew now has a package for this repo, called `python-yq` (https://github.com/Homebrew/homebrew-core/pull/29776).

**Comment by developedsoftware** [comment]
> I have installed yq via brew but xq doesn't exist. What am I missing?

Did you ever resolve this? Also looking for the xq package

**Comment by lonkaut** [comment]
Kislyuk was right.  I did a `brew install python-pip`. Then `pip install yq`. It's wholely built in Python.

**Comment by developedsoftware** [comment]
> Kislyuk was right. I did a `brew install python-pip`. Then `pip install yq`. It's wholely built in Python.

Yeah thats what I ended up doing anyway. Be nice if there was a brew package for it I must say!

**Comment by prodrammer** [comment]
As stated in the above comments, `brew install python-yq` will install this project, which also makes `xq` available from your shell.
