### ISSUE TITLE
`--argfile` with command substitution is broken

### ISSUE THREAD

**Issue by pisto** [kislyuk/yq#116]
Version: 2.11.1

Command substitution is very handy to combine multiple documents:
```
[pisto@kp ~]$ jq -n --argfile a <(echo '{"a":"hello"}') --argfile b <(echo '{"b":"world"}') '$a + $b'
{
  "a": "hello",
  "b": "world"
}
```
but it does not work in `yq`:
```
[pisto@kp ~]$ echo | yq -n --argfile a <(echo '{"a":"hello"}') --argfile b <(echo '{"b":"world"}') '$a + $b'
jq: Bad JSON in --argfile a /dev/fd/63: Could not open /dev/fd/63: No such file or directory
```
This is due to the fact that `yq` spawns another process, and there file descriptor 63 appears to be invalid. It appears that the fd is being [`FD_CLOEXEC`](https://www.gnu.org/software/libc/manual/html_node/Descriptor-Flags.html)'d, but I cannot tell why.

**Comment by kislyuk** [comment]
This is fixed in yq v2.12.1, thanks for reporting.
