### ISSUE TITLE
Should `tomlq` be called `tq` to be consistent with `xq`, `yq` and `jq`?

### ISSUE THREAD

**Issue by dcompoze** [kislyuk/yq#131]
I've noticed that he toml utility is called `tomlq` while the other utilities are called `xq`, `yq` and `jq`. Is there a reason for the naming choice? Seems like it wouldn't name-clash with any other unix tools and would be more consistent.

**Comment by kislyuk** [comment]
tq is the name of an existing utility (https://manpages.ubuntu.com/manpages/focal/en/man1/tq.1.html) so tomlq will remain named as it is.
