### ISSUE TITLE
xq: Bug with --slurpfile?

### ISSUE THREAD

**Issue by PenelopeFudd** [kislyuk/yq#132]
Hi;

This example generates half xml/half internal-format output:
```bash
cat << 'EOF' > a.json
[  { "copy": { } } ]
EOF

xq -x --xml-root=a --slurpfile a a.json '$a' <<< '<a/>'

<a>[OrderedDict([('copy', OrderedDict())])]</a>
```

I'm guessing `--slurpfile a a.json` has a bug, because replacing it with `--argjson a "$(cat a.json)"` works as expected.

Thanks for the fine program!  :-)

**Comment by kislyuk** [comment]
Sorry about missing this issue, @PenelopeFudd. I just ran your example and confirmed that this bug has since been fixed. Thank you for reporting.
