### ISSUE TITLE
Object of type bytes is not JSON serializable.

### ISSUE THREAD

**Issue by normanr** [kislyuk/yq#140]
When trying to parse a file with !!binary data:
```
example: !!binary SGVsbG8gd29ybGQhCg==
```
yq fails with:
```
yq: Error running jq: TypeError: Object of type bytes is not JSON serializable.
parse error: Unfinished JSON term at EOF at line 1, column 12
```
Adding `-y` or `-Y` doesn't help (although prevents the second line from being printed).

**Comment by kislyuk** [comment]
Thank you for reporting. Fixed in v2.14.0.
