### ISSUE TITLE
Wrong charset is used when reading stdin on Windows

### ISSUE THREAD

**Issue by bergerst** [kislyuk/yq#142]
To reproduce:

1. Execute `echo 'test: Äöü' | yq` on Windows
2. The following is printed:
```
{
  "test": "Ã„Ã¶Ã¼"
}
```

The same bug happens when reading from an UTF-8 encoded file.

This prevents me from using it on Windows.

**Comment by kislyuk** [comment]
yq is completely agnostic to the encoding being used. We do not hardcode utf-8 (which you should use) anywhere in the codebase. The encoding to use is automatically selected by Python. I recommend that you check your system configuration to track which encoding is used by Python by default - I don't really have a good idea of how this is done on Windows, nor do I have any desire to find out. You might also consider using WSL.

**Comment by kislyuk** [comment]
I am going to close this issue for now as it does not appear to be a bug in yq. If you have specific suggestions
