### ISSUE TITLE
yq rewrites key 'on' to 'true'

### ISSUE THREAD

**Issue by kftsehk** [kislyuk/yq#148]
happens in github action yaml

test.yaml:
```yaml
on: push
```

test case:
```
yq --version
# yq 2.14.0

jq --version
# jq-1.6

yq -i -S -Y test.yaml && cat test.yaml
# 'true': push
```

the output is not equivalent to `on: push`, in my opinion, `on` to `true` transform should only be applied to values, not keys

Current workaround is
```yaml
'on': push
```

**Comment by kftsehk** [comment]
Thanks for explaining, the good side is there is a workaround.

**Comment by kislyuk** [comment]
v3.0.1 enables YAML 1.2 support, so this issue should now be fixed.
