### ISSUE TITLE
Use python built in TOML support?

### ISSUE THREAD

**Issue by daurnimator** [kislyuk/yq#154]
Python 3.11 now includes TOML support in the standard library.
https://peps.python.org/pep-0680/

Could that be used instead of the current TOML dependency?

**Comment by kislyuk** [comment]
Thanks for the heads up. I would love to do that. Currently I'm focused on other things so I welcome PRs to implement that. Until Python 3.10 reaches EOL, we will have to operate two code paths, with a version dependent dependency and conditional import.

**Comment by mgorny** [comment]
This is already part of #153.

**Comment by kislyuk** [comment]
@mgorny thanks, but that PR is not ready to be merged yet. I responded with feedback in the PR.

**Comment by kislyuk** [comment]
As noted in #153, the python built in TOML support is not ready to be used by this project, because it's not a functional parser/serializer.
