### ISSUE TITLE
[xq] Parse optional schema (xsd) file to determine the types for better json output

### ISSUE THREAD

**Issue by tempelmann** [kislyuk/yq#155]
This is a feature review. When I parse an XML file, even when it points to a valid xsd file (online), there's no attempt to load it, nor do I see an option to supply one on the local file system.

It would be great if the xsd could be used to learn about the types of data, especially when they're a number or a boolean.

**Comment by kislyuk** [comment]
Thanks for your suggestion. I don't consider this feature to be in scope for xq - you may want to look at using other libraries like xmlschema in a script to accomplish this.
