### ISSUE TITLE
Some advice about license compliance

### ISSUE THREAD

**Issue by Ashley123456789** [kislyuk/yq#157]
Hello, such a nice repository benefits me a lot and so kind of you to make it open source!

**Question** 
There’s some possible legal issues on the license of your repository when you combine numerous third-party packages.
For instance, _hashlib and datetime_ you imported are licensed with _Python Software Foundation License and Zope Public License (ZPL 2.1),_ respectively. 
However, the _Apache License_ of _your repository_ are less strict than above package licenses on some terms, which has violated the whole license compatibility in your repository and may bring legal and financial risks.

**Advice** 
You can select another proper license for your repository, or write a custom license with license exception if some license terms couldn’t be summed up consistently.

Best wishes!

**Comment by kislyuk** [comment]
Hi, I have noticed that you have sent a number of notices like this one. Please stop sending these uninformed messages to OSS maintainers until you have had a chance to review your advice with an OSS licensing expert. You are mistaken about how open source licenses interact, and your message can be construed as trying to spread FUD (fear, uncertainty, and doubt) about software whose authors have done nothing wrong and face no risks of the kind you describe.
