### ISSUE TITLE
add `fromyaml` like jqs `fromjson`

### ISSUE THREAD

**Issue by cwrau** [kislyuk/yq#159]
Would it be possible to add `fromyaml`? So we can parse sub-strings from yaml?

**Comment by kislyuk** [comment]
Not possible in the current architecture. yq is a wrapper around jq, and we don't have any way to add these kinds of commands to jq.

**Comment by kislyuk** [comment]
I'm going to close this issue for now since it's not planned to do anything about it. If you have any other thoughts, feel free to add them here or open a new issue.

**Comment by cwrau** [comment]
Ah, I understand 😕
