### ISSUE TITLE
ConstructorError: found unconstructable recursive node

### ISSUE THREAD

**Issue by 2rs2ts** [kislyuk/yq#167]
I have some YAML that's like this:

```yaml
--- &1
foo: bar
recursive: *1
```

Trying to parse this at all (even using a filter as simple as `.foo`) raises the following error:

```
yq: Error running jq: ConstructorError: found unconstructable recursive node
  in "<stdin>", line 1, column 5.
```

I understand that it's sort of my fault that there is infinite recursion in my YAML, but I think that it would be good to be able to work around heavy recursion, including the infinite case, somehow. Perhaps a command line argument to set a maximum recursion depth?

**Comment by kislyuk** [comment]
Have you tried the `--no-expand-aliases` option?

**Comment by kislyuk** [comment]
Confirmed that the example cited works with `--no-expand-aliases`, closing.
