### ISSUE TITLE
Read YAML and output TOML

### ISSUE THREAD

**Issue by Karmaki** [kislyuk/yq#180]
I was wondering if there is a way to take a YAML file as input, and output a TOML file? Since you are handling both formats, I thought it should be possible, but if it is, I do not find how.

Thanks in advance for your answer, and thanks for your nice tool.

**Comment by kislyuk** [comment]
Try this:
```
cat pyproject.toml | tomlq --yaml-output . > pyproject.yaml
```
```
cat pyproject.yaml | yq --toml-output . > pyproject.toml
```

**Comment by kislyuk** [comment]
The option is undocumented on purpose. It has been there for as long as TOML support has been there.

Can you paste the contents of your pyproject.toml?

**Comment by kislyuk** [comment]
Ah, I think I know what's happening there. You are trying to convert a YAML file with null values into TOML, which does not support them.

**Comment by kislyuk** [comment]
Filed #183

I'm going to close this issue since there is no bug that I can identify aside from that.

**Comment by Karmaki** [comment]
Sorry for the delay of my answer. Indeed, this was the problem. Thank you very much for your answer and for the new ticket.
