### ISSUE TITLE
[bug] Version 3.3.0 breaks float parsing

### ISSUE THREAD

**Issue by cwrau** [kislyuk/yq#187]
The following yaml:

```yaml
test: 0.0004
```

Results in the following json with yq 3.2.3:

```json
{
  "a": 0.0004
}
```

and the following with yq 3.3.0:

```json
{
  "a": "0.0004"
}
```

See the added quotes, meaning the floating number is now a string

**Comment by kislyuk** [comment]
Thanks for reporting. Fix released in v3.3.1.
