### ISSUE TITLE
Why block current versions of Python build tooling?

### ISSUE THREAD

**Issue by alerque** [kislyuk/yq#190]
https://github.com/kislyuk/yq/blame/913a2ac6d82bf389abacc8f372536a836a3d3075/setup.py#L18

Can I ask why this was done?

From my perspective this just makes distro packaging harder. Now I have to figure out why this supposedly matters and add a patch to revert it to keep the Arch Linux package up to date, plus deal with whatever supposedly doesn't work right with the current version of the tooling...

**Comment by alerque** [comment]
Okay I see the reason is #190, but the fix is worse than the bug!

**Comment by alerque** [comment]
For the purposes of distro packaging I've hacked out this change and also manually fixed the version while waiting for upstream fixes.

https://gitlab.archlinux.org/archlinux/packaging/packages/yq/-/blob/3.4.2-1/PKGBUILD?ref_type=tags#L27

**Comment by kislyuk** [comment]
Thank you for your interest in yq and your effort in packaging it. I will remind you to please remain polite and civil when conversing with package maintainers, consistent with the code of conduct for this project.

You can read more about the reason for this change in https://github.com/kislyuk/yq/issues/189.

**Comment by kislyuk** [comment]
Fix released in version 3.4.3 after I received support from upstream.
