### ISSUE TITLE
Error when name contains a dash (-)

### ISSUE THREAD

**Issue by wadewegner** [kislyuk/yq#20]
`test.yaml` contents:

```
test: "test output"
my-test: "my-test output"
```

Error when trying to access `my-test`:

```
❯ cat test.yml | yq .test
"test output"
❯ cat test.yml |yq .my-test
jq: error: test/0 is not defined at <top-level>, line 1:
.my-test
jq: 1 compile error
```

**Comment by kislyuk** [comment]
See https://github.com/stedolan/jq/issues/38.

**Comment by PetterSa** [comment]
For others that might find this in the future and tries something like this 
`cat ${HOME}/.kube/config | yq ."current-context"`
without success, the solution is to escape the quotation marks. 

For example: 
`cat ${HOME}/.kube/config | yq .\"current-context\"`
`cat ${HOME}/.kube/config | yq .[\"current-context\"]`

**Comment by kislyuk** [comment]
Single quotes are useful too: `yq '.["foo"]'`
