### ISSUE TITLE
LICENSE file is missing in source distribution

### ISSUE THREAD

**Issue by sodre** [kislyuk/yq#24]
I am packaging yq for availability through [conda-forge](https://github.com/conda-forge) and I noticed that the LICENSE file is not being packed in the source distribution. 

Can you add the LICENSE in your next release of YQ?

**Comment by kislyuk** [comment]
No. The license is noted in setup.py.

**Comment by sodre** [comment]
kislyuk, the Apache license file should be included with the source distribution as well. But it is up to you if you still want to fix it.

**Comment by kislyuk** [comment]
The repo you're looking at *is* the source distribution.

**Comment by jakirkham** [comment]
I think we are overthinking this. All that is being asked for is this ( https://github.com/kislyuk/yq/pull/25 ).

**Comment by kislyuk** [comment]
OK, thanks for your contribution @jakirkham.
