### ISSUE TITLE
No man entry

### ISSUE THREAD

**Issue by aepod** [kislyuk/yq#26]
`man yq
No manual entry for yq
`

I would suggest a man entry.

**Comment by kislyuk** [comment]
The manual page can be generated by running `make -C docs man` in the yq repo directory.

The resulting man page will be in `docs/_build/man/yq.1`. You should be able to view it using `less`.

Installing the man page in a systemwide location is not something that I can do as a Python package distributor. Setuptools and pip provide no capability to do this, so whoever packages yq for Linux distributions will have to install it.

**Comment by christmart** [comment]
Did you remove the possibility to build a manpage? I can't find it in version 3.1.0.

**Comment by SuperSandro2000** [comment]
It was deleted with https://github.com/kislyuk/yq/commit/d7f5ed25f7fb165c45ce841da6001e6f4d91772f
