### ISSUE TITLE
Preserve comments

### ISSUE THREAD

**Issue by mkielar** [kislyuk/yq#28]
This file:
```
foo: bar
# This is commented out - baz: bazzz
```
when passed through `yq w test.yaml foo newValue`, returns:
```
foo: newValue
```

One of the main advantages of using YAML over JSON is to be able to put comments into the file. This functionality is lost with current version of `yq`.

**Comment by kislyuk** [comment]
This is unlikely to happen. JSON does not support comments, jq does not support JSON-like language dialects that support them, and any transformation will inevitably be lossy as it will transfer comments from an out-of-band channel to in-band.

You're welcome to suggest a design that you think will be preferable.

**Comment by kislyuk** [comment]
Also, looking at the syntax of the command that you cited, you seem to be in the wrong repo.

**Comment by mkielar** [comment]
facepalm ;-)
