### ISSUE TITLE
Tilde character `~` wrong behavior

### ISSUE THREAD

**Issue by Toshik** [kislyuk/yq#31]
`echo "aaa: 1" | yq ".aaa=\"abc\"" --yaml-output` outputs `aaa: abc` and it is correct.

but if we use `~`: 
`echo "aaa: 1" | yq ".aaa=\"~\"" --yaml-output` outputs `aaa: '~'` which is incorrect. 
Expected output is `aaa: ~` - without quotation

**Comment by kislyuk** [comment]
I'm pretty sure that's wrong. `~` is a synonym for a `null` literal in YAML.

**Comment by kislyuk** [comment]
Use `null`. Remember, the filters are jq filters (so based on the JSON syntax). In jq, ~ is not a valid literal, but `null` is.

**Comment by kislyuk** [comment]
(In your example, you'll also need to drop the quotes around the value.)
