### ISSUE TITLE
How do I query for fields with dashes in them?

### ISSUE THREAD

**Issue by tlycken** [kislyuk/yq#32]
I have the following yaml file `foo.yaml`:

```
echo
```

Now, trying `yq .bar.some-data foo.yaml` or `yq .bar['some-data'] foo.yaml` doesn't give me `y`, but errors:

```
$ yq .bar.some-data foo.yaml
jq: error: data/0 is not defined at <top-level>, line 1:
.bar.some-data
jq: 1 compile error

$ yq .bar['some-data'] foo.yaml
jq: error: some/0 is not defined at <top-level>, line 1:
.bar[some-data]
jq: error: data/0 is not defined at <top-level>, line 1:
.bar[some-data]
jq: 2 compile errors
```

What is the correct way to query for those properties?

**Comment by kislyuk** [comment]
You need to quote the key: `yq '.bar["some-data"]'`. See the jq documentation.
