### ISSUE TITLE
Preserve a YAML 'literal block' (using |), or a 'folded block' (using '>')

### ISSUE THREAD

**Issue by arno01** [kislyuk/yq#36]
yq -y needs to preserve a 'literal block' (using |), or a 'folded block' (using '>')

## Original YAML

```
$ cat y
some:
  file: |
    hello world
    line1
    line2
```

## yaml 2 yaml

It gives different output:

```
$ cat y | yq -y .
some:
  file: 'hello world

    line1

    line2

    '
```

Would it be possible to preserve the original YAML 1-1 when ``yq`` is instructed to output YAML ?

**Comment by kislyuk** [comment]
Thanks for reporting - unfortunately this is tricky since after round-tripping through JSON, there is no metadata on what kind of block the original text was. We could probably configure PyYAML to write all multiline strings as literal blocks or folded blocks, but I'm not sure if that's always the best thing to do, or what else to do to improve this.

**Comment by varac** [comment]
I see two issues:

1. Added newlines between the 3 lines in the example, completely breaking/altering the value
1. yq should preserve the type, and not replace a literal block or folded block with a quoted multiline string.

Both should be fixed imho but I guess the first one is easier.. ?

Is there any corresponding issue at the PyYAML that would help yq with this ?

**Comment by kislyuk** [comment]
The first observation that you make is not an issue. The two constructs in the description are equivalent in YAML. See the YAML spec and https://yaml-multiline.info/ for a thorough explanation of this.

As I mentioned in my previous comment, there is no metadata preserved in JSON on what kind of block the original string was. As such there is no obvious way to solve the second issue that you mention under the design constraints of yq.

**Comment by varac** [comment]
Awesome, thx !!

**Comment by varac** [comment]
Is this the desired behaviour ?

This looks pretty well:

```
❯ cat y
some:
  file: |
    hello world
    line1
    line2

❯ yq -Y . < y
some:
  file: |
    hello world
    line1
    line2

❯ yq -Y .some < y
file: |
  hello world
  line1
  line2
```

But when I query the exact key, the literal block is not presered anymore:

```
❯ yq -Y .some.file < y
'hello world

  line1

  line2

  '
```

**Comment by kislyuk** [comment]
Yes. You don't need -Y when all you're doing is extracting the leaf node.

**Comment by adrian-gierakowski** [comment]
just wanted to circle back to this: I understand it's not possible to preserve the kind of blocks, but would it be possible to provide a command line option to default the block kind to a chosen one in case a newline character is detected in the value? 

I'd like to always use one of the multi-line blocks as I run `diff` on the of to commands piped through `yq`, and any changes in multi line values become unreadable

for example:

```sh
echo 'jsonObject: |-
  {
    "a": 1,
    "b": 2,
  }' | yq -y
```

gives me:

```yaml
jsonObject: "{\n  \"a\": 1,\n  \"b\": 2,\n}"
```

which is not very "diffable"

for examplet:

```fish
diff --color=always (echo 'jsonObject: |-
  {
    "a": 1,
    "b": 2,
  }' | yq -y | psub) (echo 'jsonObject: |-
  {
    "a": 1,
    "c": 2,
  }' | yq -y | psub)
```

gives me:

```diff
1c1
< jsonObject: "{\n  \"a\": 1,\n  \"b\": 2,\n}"
---
> jsonObject: "{\n  \"a\": 1,\n  \"c\": 2,\n}"
```

vs 

```fish
diff --color=always (echo 'jsonObject: |-
  {
    "a": 1,
    "b": 2,
  }' | psub) (echo 'jsonObject: |-
  {
    "a": 1,
    "c": 2,
  }' | psub)
```


```diff
4c4
<     "b": 2,
---
>     "c": 2,
```
