### ISSUE TITLE
xq --xml-output not preserving xml declaration

### ISSUE THREAD

**Issue by lyenliang** [kislyuk/yq#37]
I have an `test.xml` file which contains `<?xml version="1.0" encoding="UTF-8" standalone="no"?>` at its first line.

When I run `xq --xml-output '.' test.xml`, the generated xml doesn't contain `<?xml version="1.0" encoding="UTF-8" standalone="no"?>`. 

It is possible to modify `xq` so that it preserves the XML declaration?

**Comment by kislyuk** [comment]
With v2.7.1, now it is.

Use `xq --xml-output --xml-dtd`.
