### ISSUE TITLE
Allow streams of YAML documents as input

### ISSUE THREAD

**Issue by ssssam** [kislyuk/yq#39]
Hi!
I am finding yq very useful, but there is one thing that would make it better.
YAML is a superset of JSON, so I imagined that yq's input format would be a superset of jq's input format. However, this turns out not to be true because yq only parses a single YAML object and raises an error if there are multiple objects as input.

For example, if I run this command:

```echo \"Hi\" | jq '{ hey: . }, { ho: . }' | yq . -y```

I get the following output:

```
yq: Error running jq: ParserError: expected '<document start>', but found '{'
  in "<stdin>", line 4, column 1.
```

However, I'd expect to see the following output:

```
- hey: Hi
- ho: Hi
```

Is this something you are interested in supporting?

(edit: I realise that piping `jq` into `yq` is pointless. My actual use case is that I am developing a tool which outputs data as a JSON stream, and I would like to be able to pipe its output directly into `yq . -y` to convert it back to YAML and optionally run some jq filters on it. I can achieve this already by piping the ouptut to `jq -s '[ . ]' | yq .[] -y` but it would be nice if I could just use `yq . -y` in place of that)

**Comment by kislyuk** [comment]
You can definitely pipe multiple documents into yq. YAML is not a superset of JSON when it comes to multi-document streams. You must separate documents with `---`.

**Comment by lucasfcnunes** [comment]
For a single valid YAML per line:
```sh
$ echo "aaaa\nbbbbb" | awk '{print $0, "\n---"}' | yq -P
aaaa
---
bbbbb
---
$ echo "{"a": 1, "b": "a"}\nbbbbb" | awk '{print $0, "\n---"}' | yq -P
a: 1
b: a
---
bbbbb
---
```
