### ISSUE TITLE
Create a Debian package

### ISSUE THREAD

**Issue by dlresende** [kislyuk/yq#43]
`yq` is currently distributed as a Homebrew formula (#11), and that's awesome!

As a suggestion, I think it would be great if `yq` was distributed as a [Debian package](https://askubuntu.com/a/1451/118393) as well. This would allow more folks to easily install it in Debian-compatible Linux distributions (like Ubuntu), doing something like:

```sh
sudo add-apt-repository ppa:kislyuk/yq
sudo apt update
sudo apt install yq -y
```

This would also make a real case for using `yq` more broadly in server scripts, Linux-based developer workstations, etc.

**Comment by mcepl** [comment]
Packages should not be maintained upstream. File RFP bug at https://www.debian.org/devel/wnpp/

**Comment by kislyuk** [comment]
I will not be maintaining a PPA and I will not be maintaining a Debian package in this repository. If someone wants to create a Debian or Ubuntu package, please feel free to do so.
