### ISSUE TITLE
unexpected keyword argument 'allow_abbrev'

### ISSUE THREAD

**Issue by gdmsl** [kislyuk/yq#47]
Hello. I get this error everytime I try to launch `yq` with or without arguments (also the examples in in  README.md don't work).

~~~
Traceback (most recent call last):
  File "/usr/bin/yq", line 11, in <module>
    load_entry_point('yq==2.7.2', 'console_scripts', 'yq')()
  File "/usr/lib/python3.7/site-packages/yq/__init__.py", line 119, in main
    parser = get_parser(program_name)
  File "/usr/lib/python3.7/site-packages/yq/__init__.py", line 96, in get_parser
    parser = Parser(**parser_args)
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'
~~~

**Comment by kislyuk** [comment]
Thanks for reporting.

It looks like perhaps your `argparse` library is from an older version of Python. How did you install `yq`?

Can you paste the output of the following commands:
```
echo $PYTHONPATH
```
```
cat /usr/bin/yq
```
Then, using the path to Python that appears in the first line of that output (for example, in my case it's `#!/usr/local/opt/python/bin/python3.6`):
```
/usr/local/opt/python/bin/python3.6 --version
```
```
/usr/local/opt/python/bin/python3.6 -c 'import argparse; print(argparse.__file__)'
```

The argument `allow_abbrev` was introduced in Python 3.5: https://docs.python.org/3/library/argparse.html#allow-abbrev. `yq` tests the version of Python before passing the argument, and only does so if the version is 3.5 or above.

**Comment by gdmsl** [comment]
So I have this lines in my `.profile`.

```bash
# python path
export PYTHONUSERBASE="$HOME/Variable/python3"
export PYTHONPATH="$PYTHONUSERBASE/lib/python3.7/site-packages:$PYTHONPATH"
export PATH="$PYTHONUSERBASE/bin:$PATH"
```
which lead to the following python path

```
$ echo $PYTHONPATH
/home/gdmsl/Variable/python3/lib/python3.7/site-packages:
```

I installed yq from AUR (Archlinux)

```
$ which yq
/usr/bin/yq

$ head /usr/bin/yq
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'yq==2.7.1','console_scripts','yq'
__requires__ = 'yq==2.7.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('yq==2.7.1', 'console_scripts', 'yq')()
    )
```

then

```
$ python --version
Python 3.7.2
```

and finally

```
$ python -c 'import argparse; print(argparse.__file__)'
/usr/lib/python3.7/argparse.py
```

**Comment by kislyuk** [comment]
Can you check that the file in /usr/lib/python3.7/argparse.py is identical to https://github.com/python/cpython/blob/3.7/Lib/argparse.py?

**Comment by kislyuk** [comment]
Closing due to lack of response.

**Comment by jonathan-neufeld-asurion** [comment]
I am running into this issue now as well, and to answer your question, they are _very_ different.
