### ISSUE TITLE
yq-2.7.2 is failing with "jq: error: read/0 is not defined at <top-level>, line 1"

### ISSUE THREAD

**Issue by gnawhleinad** [kislyuk/yq#50]
```
$ yq --version
yq 2.7.2
$ jq --version
jq-1.6
$ cat hodor.yml 
- hodor
$ yq read hodor.yml 
jq: error: read/0 is not defined at <top-level>, line 1:
read
jq: 1 compile error
```

I installed `yq` and `jq` via `brew` (`python-yq` and `jq`, respectively).

**Comment by kislyuk** [comment]
You are confusing this with another package by the same name. The syntax of yq mirrors that of jq, so there is no "read" command, just a filter, the identity filter being `.`:
```
yq . hodor.yml
```
