### ISSUE TITLE
Convert JSON to YAML

### ISSUE THREAD

**Issue by alerque** [kislyuk/yq#51]
JSON should be supported as an input format. My project(s) use YAML internally, but a lot of the external data they source comes in from JSON formats. Considering that it gets processed with `yq` anyway and `yq` is making a round trip to JSON, it seems kind of silly that there isn't an `--json-input` or similar flag to bypass the first half of the round trip. This would allow `yq` to work as a JSON→YAML conversion tool, reducing my project dependencies.

**Comment by kislyuk** [comment]
I'm not sure what you're asking for - YAML was designed to be a superset of JSON, so JSON is supported as an input format by definition. Are you having trouble feeding valid JSON to `yq -y .`?

**Comment by alerque** [comment]
Say what? All this time I've been jumping through extra hoops when I could just chop the json→yaml conversion out of my pipeline? I feel really dumb now.

Actually though, thanks for being very specific in your tip: the keyword being _valid JSON_. It looks like what I was trying to do yesterday didn't work when I tried to stuff it directly into `yq`, but the fault for that lies with the invalid original syntax.

**Comment by alerque** [comment]
P.S. I wonder if this should be mentioned more specifically in the documentation. I combed through the docs looking for this specifically. I suspect I wouldn't be the only one to benefit from having the possibility shoved in my face.
