### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by lad** [kislyuk/yq#54]
Documentation in the main readme suggests using a similar syntax to JQ, but the basic example doesn't seem to work:

cat input.yml | yq .foo.bar

On OSX:

```
$ brew install yq
$ cat > input.yml
foo:
 - bar: "text"
   value: 200
baz:
 - bar: "blah"
   value: 100
^D
$ cat ./input.yml | yq .foo.bar
Error: unknown command ".foo.bar" for "yq"
Run 'yq --help' for usage.
2019/04/12 16:18:29 unknown command ".foo.bar" for "yq"
```

**Comment by kislyuk** [comment]
You are confusing yq with another tool by the same name. To install yq via brew, run `brew install python-yq`.
