### ISSUE TITLE
Support YAML with multiple docs

### ISSUE THREAD

**Issue by r4j4h** [kislyuk/yq#6]
The YAML standard allows embedding multiple YAML documents into one by separating them with `---` lines.

When `yq` is given these as input, it errors out with:

```
yq: Error while running jq: ComposerError: expected a single document in the stream
  in "<stdin>", line 2, column 1
```

I have a tool that can output yaml or json and when it outputs json it returns two objects concatenated, something like:

```
{
   'thing': 1
}
{
  'thing': 2
}
```

Interestingly, if I pass these directly to `jq` it handles them cleanly. It runs the given command on each document.

Because `yq` wraps `jq` it seems like it should be able to handle this in a like manner.

**Comment by kislyuk** [comment]
You raise a good point about mirroring the behavior of `jq`. I took a stab at making both `yq` and `yq -y` mirror the multi-doc behavior and released it in v2.3.0, please test.

**Comment by r4j4h** [comment]
From preliminary testing it works a treat! Thanks!! :)

**Comment by jurgenweber** [comment]
can I pull the different documents out somehow?

**Comment by jurgenweber** [comment]
I was about to get around this:

```
#!/bin/bash

file="${1}"

#are there many yaml documents in this file?
length=$(yq -s '. | length' ${file})
count=0

while [ "${count}" -lt "${length}" ]; do
  yq -s ".[${count}]" "${file}" | kubetest --verbose

  count=$(( count + 1 ))

done
```
