### ISSUE TITLE
xq: Error running jq: ExpatError: not well-formed

### ISSUE THREAD

**Issue by cup** [kislyuk/yq#76]
Here:

https://github.com/kislyuk/yq#xml-support

It says:

> Roundtrip transcoding is available with the `xq --xml-output` / `xq -x`
> option.

but it doesnt actually work that way:

~~~
$ echo '{"foo": "bar"}' | xq -x .
xq: Error running jq: ExpatError: not well-formed (invalid token): line 1,
column 0.
~~~

This does work:

~~~
$ echo '{"foo": "bar"}' | yq -x .
<foo>bar</foo>
~~~

**Comment by cup** [comment]
https://github.com/kislyuk/yq/issues/33

**Comment by kislyuk** [comment]
You misunderstood the documentation. xq expects XML input, while yq expects JSON input. `-x` controls the output format.

**Comment by cup** [comment]
@kislyuk what documentation?

It seems that you are saying the quoted documentation is for `xq -x`. If thats the case, then `yq -x` isnt actually documented.

**Comment by kislyuk** [comment]
Correct.
