### ISSUE TITLE
Key "on" mistakenly parsed

### ISSUE THREAD

**Issue by evertonfraga** [kislyuk/yq#78]
Hi, kudos for the project. It is really useful to me.

However, i just bumped into an issue. while converting a specific key. `on:` gets translated to `true`. 

#### Environment
- Python versions I tested: 3.6.0, 2.7.15
- yq version: 2.9.2
- MacOS

Reproducible steps, using `yq` own test files:
```
curl https://raw.githubusercontent.com/kislyuk/yq/master/.github/workflows/pythonpackage.yml | yq .
```

Output:
```
{
  "name": "Python package",
  "true": [  <====== HERE
    "push"
  ],
  "jobs": {
    "build": {
…
(the rest of the output is OK)
```

**Comment by kislyuk** [comment]
This is not a problem with yq, but with the YAML parser that it uses. PyYAML does not support YAML 2.0, which eliminated the broken behavior that you point out. Feel free to upvote the issue at https://github.com/yaml/pyyaml/issues/116.

**Comment by evertonfraga** [comment]
Much appreciated. I was now generating a test case for yq, but that won't be necessary. 

upvoted.

**Comment by evertonfraga** [comment]
I found an obvious workaround and I'm just posting here for documentation sake. It works when I changed `on:` to `"on":`, in the yaml file.

That works for me now, feel free to close the issue.
