### ISSUE TITLE
Running via "python3 -m" doesn't work

### ISSUE THREAD

**Issue by pfalcon** [kislyuk/yq#81]
It's not always comfortable to rely on running via "yq" wrapper. Python offers its own way to execute arbitrary modules/packages, which doesn't rely on the setup of the underlying system (PATH, shebang support, etc.), It's `-m` switch to the interpreter, e.g. `python3 -m tabnanny`.

But yq unfortunately doesn't work that way:
~~~
$ python3 -m yq
/usr/bin/python3: No module named yq.__main__; 'yq' is a package and cannot be directly executed
~~~

Should be pretty easy to fix of course.

All that with:
~~~
$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yq
>>> yq.__version__
'2.10.0'
~~~

**Comment by Hellomello13** [comment]
attempted a fix that worked for me here: https://github.com/kislyuk/yq/pull/82

**Comment by pfalcon** [comment]
@Hellomello13, thanks for looking into this issue!

**Comment by pfalcon** [comment]
@kislyuk, ping, any response here? Thanks!

**Comment by kislyuk** [comment]
LGTM thanks.
