### ISSUE TITLE
yq r somefile.json returns json as it is.

### ISSUE THREAD

**Issue by vaibhavmehrotra94** [kislyuk/yq#85]
I am trying to convert a JSON file to YAML. but it doesn't work like it is supposed to.

I tried using version yq version :- 2.4.0. it worked perfectly on that.

But on a different system when i used with version :- 3.0.1 it returns the same JSON as it is.

I have attached a sample below
![yq sample](https://user-images.githubusercontent.com/31144001/73723992-5bb89280-4750-11ea-8e30-37b19e43b7ef.png)

**Comment by kislyuk** [comment]
This is not the yq you're looking for.
