### ISSUE TITLE
could you provide some samples for how to parse xml file with yq?

### ISSUE THREAD

**Issue by ozbillwang** [kislyuk/yq#87]
the README is not clear enough to deal with xml. 

For example, I have a pom.xml (https://github.com/codecov/example-java/blob/master/pom.xml). and I would like to 

1. get the version

the result should be `1.0-SNAPSHOT`

I tried several commands, but no output

```
cat pom.xml |yq '//project//version'

cat pom.xml |yq .project.version
```

2. remove the version line out of pom.xml

So the output will have the most lines, except `<version>1.0-SNAPSHOT</version>`

how do I get the result with yq?

By the way, I found a bug in yq. If pom.xml has tag (\t) in the xml file, it will report error

```
yq: Error running jq: ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<stdin>", line 31, column 1.
```

**Comment by kislyuk** [comment]
The README file does provide sufficient information on how to handle XML files. It provides examples of using the `xq` executable for this. You tried to use the wrong executable.

The command you're looking for is `xq -r .project.version pom.xml`.

**Comment by ozbillwang** [comment]
This is little confused me, but thanks for your command. I got the result I need with `xq`

**Comment by ozbillwang** [comment]
So why not merge two commands into one? As default, the input file should be yaml. 

when deal with xml file, we can set --xml <pom.xml> and feed to yq command.
