### ISSUE TITLE
emulate -i support

### ISSUE THREAD

**Issue by rbtcollins** [kislyuk/yq#9]
jq has a feature request open to support sed-like in-place editing of files. It would be lovely if yq were to support that in advance.

e.g. `yq '(.foo.bar=3)' -i foo.yaml` would replace foo.yaml in-place, safely, with an implied -y. (write a temp file, close the source file, rename the temp file over the source file) [on windows, a delete or mv of the source file is also needed in there because 👎 but hey, close as we can get.

I'd be happy to put a patch up if this feature request seems reasonable.

**Comment by kislyuk** [comment]
Thanks for the suggestion, but I would prefer to wait until upstream (https://github.com/stedolan/jq/issues/105) adds this feature.

**Comment by kislyuk** [comment]
Actually, thinking about it a bit more, the strategy you describe doesn't sound too bad (if yq makes `-i` imply `-y`, then we don't have to special case the branch that captures jq stdout).

I guess I'm OK with it. Please send the PR.
