### ISSUE TITLE
Yaml output converts exponential strings to a number

### ISSUE THREAD

**Issue by MadVikingGod** [kislyuk/yq#91]
When using the yaml output, yq will convert strings containing exponential numbers to a number.

```
echo 'key: "1e+06"' > test.yaml
yq -y test.yaml
>  key: 1e+06
```
Expected output
```
yq -y test.yaml
>  key: "1e+06"
```

This does not happen with the json output.
```
yq . test.yaml
>  {
>    "key": "1e+06"
>  } 
```
Nor does this effect lists, eg. `echo '- "1e+06"' > test.yaml`

**Comment by kislyuk** [comment]
From the YAML format perspective, that `1e+06` is not a number; it's parsed and emitted as a string. The default output style is unquoted.

You can however use `yq -Y` to preserve the input quote style, which will preserve the quotes around `1e+06`.
