### ISSUE TITLE
2 different yq?

### ISSUE THREAD

**Issue by woodcockjosh** [kislyuk/yq#98]
I think this project should be deprecated in favor of https://github.com/mikefarah/yq and those binaries pushed to pip. Pumping everything through jq is not ideal and creates problems.

**Comment by kislyuk** [comment]
For future reference, I will not tolerate these kinds of comments in my repositories. Requesting that I cease development of my project and replace it with another project which happened to start using my project's name after I began development is not acceptable discourse. It amounts to harassment, even if you may not have meant it that way.
