### ISSUE TITLE
Fresh install not working on macOS

### ISSUE THREAD

**Issue by msorens** [kislyuk/yq#99]
Just found yq and installed it on my mac via `brew install python-yq`.
Unfortunately it is not working at all for me. With any file I get this error:
```
$ cat test.yaml | yq
Traceback (most recent call last):
  File "/usr/local/Cellar/python-yq/2.10.1/libexec/bin/yq", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```
Could it have some unforeseen python pre-requisites? I am not a python user.

**Comment by kislyuk** [comment]
Can you paste the output of `pip3 show setuptools` and see if running `pip3 install --upgrade setuptools` fixes this issue?

**Comment by kislyuk** [comment]
The error you cited is related to a Python packaging toolchain installation issue, not to yq itself. If you need help, please provide the information requested.
